def render_html(report: dict) -> str:
    site = report.get("site", "unknown")
    urls = report.get("urls_crawled", 0)
    summary = report.get("summary", {})
    total = summary.get("total_issues", 0)
    by_sev = summary.get("by_severity", {})
    issues = report.get("issues", [])
    recs = report.get("recommendations", [])

    sev_color = {"High": "#ff4444", "Medium": "#ffaa00", "Low": "#44bb44"}

    rows = ""
    for i in sorted(issues, key=lambda x: {"High":0,"Medium":1,"Low":2}.get(x["severity"],3)):
        color = sev_color.get(i["severity"], "#888")
        sample_urls = "<br>".join(i["affected_urls"][:3])
        if len(i["affected_urls"]) > 3:
            sample_urls += f"<br><em>...and {len(i['affected_urls'])-3} more</em>"
        rows += f"""<tr>
            <td><span style="background:{color};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px">{i["severity"]}</span></td>
            <td><strong>{i["type"].replace("_"," ").title()}</strong><br><small>{i.get("explanation","")}</small></td>
            <td style="text-align:center"><strong>{i["count"]}</strong></td>
            <td style="font-size:11px;color:#666">{sample_urls}</td>
        </tr>"""

    rec_items = "".join(f"<li>{r}</li>" for r in recs)

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SEO Audit Report — {site}</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:Inter,system-ui,sans-serif;background:#f5f7fa;color:#1a1a2e;line-height:1.6}}
.header{{background:linear-gradient(135deg,#1a1a2e,#16213e);color:#fff;padding:40px;}}
.header h1{{font-size:28px;font-weight:700}}
.header p{{opacity:.7;margin-top:6px}}
.container{{max-width:1100px;margin:0 auto;padding:30px 20px}}
.stats{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:30px 0}}
.stat{{background:#fff;border-radius:12px;padding:20px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.06)}}
.stat .num{{font-size:36px;font-weight:700}}
.stat .label{{font-size:13px;color:#666;margin-top:4px}}
.high{{color:#ff4444}}.medium{{color:#ffaa00}}.low{{color:#44bb44}}
.card{{background:#fff;border-radius:12px;padding:24px;margin-bottom:24px;box-shadow:0 2px 8px rgba(0,0,0,.06)}}
.card h2{{font-size:18px;margin-bottom:16px;padding-bottom:10px;border-bottom:2px solid #f0f0f0}}
table{{width:100%;border-collapse:collapse}}
th{{text-align:left;padding:10px 12px;background:#f8f9fa;font-size:12px;text-transform:uppercase;color:#666;letter-spacing:.05em}}
td{{padding:12px;border-bottom:1px solid #f0f0f0;vertical-align:top}}
tr:last-child td{{border-bottom:none}}
.recs{{background:#fff8e1;border-left:4px solid #ffaa00;padding:16px 20px;border-radius:0 8px 8px 0}}
.recs li{{margin:6px 0;font-size:14px}}
.footer{{text-align:center;color:#aaa;font-size:12px;padding:20px;margin-top:20px}}
</style></head>
<body>
<div class="header">
  <div style="max-width:1100px;margin:0 auto">
    <h1>SEO Audit Report</h1>
    <p>{site} &mdash; {urls} URLs crawled</p>
  </div>
</div>
<div class="container">
  <div class="stats">
    <div class="stat"><div class="num">{urls}</div><div class="label">URLs Crawled</div></div>
    <div class="stat"><div class="num high">{by_sev.get("High",0)}</div><div class="label">High Severity</div></div>
    <div class="stat"><div class="num medium">{by_sev.get("Medium",0)}</div><div class="label">Medium Severity</div></div>
    <div class="stat"><div class="num low">{by_sev.get("Low",0)}</div><div class="label">Low Severity</div></div>
  </div>
  <div class="card">
    <h2>Recommendations</h2>
    <div class="recs"><ul>{rec_items}</ul></div>
  </div>
  <div class="card">
    <h2>Issues Found ({total} total)</h2>
    <table><thead><tr><th>Severity</th><th>Issue</th><th>Count</th><th>Affected URLs</th></tr></thead>
    <tbody>{rows}</tbody></table>
  </div>
</div>
<div class="footer">Generated by SEO Command Center &mdash; Forge Sprint 01</div>
</body></html>"""
